// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6eU6umUgfb1r7r7U9deeKQ9JP30K5X5s',
    appId: '1:104917351921:web:c33057cf8bcf57d3d09850',
    messagingSenderId: '104917351921',
    projectId: 'wave-wallet-8d668',
    authDomain: 'wave-wallet-8d668.firebaseapp.com',
    storageBucket: 'wave-wallet-8d668.firebasestorage.app',
    measurementId: 'G-6DF690216M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVrOPwpMAlhi7WEZp1pf2e_mPZfIYd25k',
    appId: '1:104917351921:android:de6cc50e1dc7bc0cd09850',
    messagingSenderId: '104917351921',
    projectId: 'wave-wallet-8d668',
    storageBucket: 'wave-wallet-8d668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoHgyfJlLf1hKebPLdZIlziVU9QN6SwPg',
    appId: '1:104917351921:ios:d263eaa83b3a8fdad09850',
    messagingSenderId: '104917351921',
    projectId: 'wave-wallet-8d668',
    storageBucket: 'wave-wallet-8d668.firebasestorage.app',
    iosBundleId: 'com.sonatel.waveWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoHgyfJlLf1hKebPLdZIlziVU9QN6SwPg',
    appId: '1:104917351921:ios:d263eaa83b3a8fdad09850',
    messagingSenderId: '104917351921',
    projectId: 'wave-wallet-8d668',
    storageBucket: 'wave-wallet-8d668.firebasestorage.app',
    iosBundleId: 'com.sonatel.waveWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6eU6umUgfb1r7r7U9deeKQ9JP30K5X5s',
    appId: '1:104917351921:web:d2f1cf6be7400371d09850',
    messagingSenderId: '104917351921',
    projectId: 'wave-wallet-8d668',
    authDomain: 'wave-wallet-8d668.firebaseapp.com',
    storageBucket: 'wave-wallet-8d668.firebasestorage.app',
    measurementId: 'G-0Q22JM8H3V',
  );
}
